version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Starting the build process..."
      - sudo yum update -y
      - sudo yum install -y httpd php
      - sudo systemctl start httpd
      - sudo systemctl enable httpd

  build:
    commands:
      - echo "Building the application..."
      - echo "<?php echo 'Hello, this is a test'; ?>" > /var/www/html/index.php
      - echo "Build completed."

  post_build:
    commands:
      - echo "Preparing the artifact for deployment..."
artifacts:
  files:
    - appspec.yml
    - scripts/start_apache.sh
    - scripts/install_dependencies.sh
    - var/www/html/index.php
 
