version: 0.2
# Creates and index file insted of using the one in GitHub
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Starting the build process..."
      - yum update -y
      - yum install -y httpd php
  pre-build:
    commands:
      - echo "This is the pre-build phase"
  build:
    commands:
      - echo "Running test..."
      - grep -Fq "Hello, this is a test!" index.html
  post_build:
    commands:
      - echo "This is the post-build phase"
