version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Starting the build process..."
      - yum update -y
      - yum install -y httpd php
  build:
    commands:
      - echo "Building the application..."
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo "Moving index.html"
artifacts:
  files:
    - appspec.yml
    - scripts/start_apache.sh
    - scripts/install_dependencies.sh
    - var/www/html/index.html
  discard-paths: no
