version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Starting the build process..."
      - yum update -y
      - yum install -y httpd php
  build:
    commands:
      - echo "Building the application..."
      - echo "<?php echo 'Hello, this is a test'; ?>" > /var/www/html/index.php
      - echo "Build completed."
  post_build:
    commands:
      - echo "Preparing the artifact for deployment..."
      - mkdir -p testcase1/var/www/html
      - mkdir -p testcase1/scripts
      - cp -r /var/www/html testcase1/var/www/html
      - cp appspec.yml testcase1/
      - cp scripts/start_apache.sh testcase1/scripts/
      - cp scripts/install_dependencies.sh testcase1/scripts/
      - echo "Artifact prepared."
artifacts:
  files:
    - testcase1/**
  discard-paths: no
