version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Starting the build process..."
      - yum update -y
      - yum install -y httpd php
  build:
    commands:
      - echo "Building the application..."
      - echo "<?php echo 'Hello, this is a test'; ?>" > /var/www/html/index.php
      - echo "Build completed."
  post_build:
    commands:
      - echo "Preparing the artifact for deployment..."
      - zip -r Output1 /var/www/html
      - zip -ur Output1 appspec.yml  #Adds appspec to the artifact
      - zip -ur Output1 /scripts/start_apache.sh
      - zip -ur Output.zip /install_dependencies.sh
      - echo "Artifact prepared."

artifacts:
  files:
    - Output1.zip
  discard-paths: no
