version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Starting the build process..."
      - yum update -y
      - yum install -y httpd php
      - sudo systemctl start httpd
      - sudo systemctl enable httpd

  build:
    commands:
      - echo "Building the application..."
      - echo "<?php echo 'Hello, this is a test'; ?>" > /var/www/html/index.php
      - echo "Build completed."

  post_build:
    commands:
      - echo "Preparing the artifact for deployment..."
      # Trabajar en el directorio actual sin crear nuevas carpetas
      - cp -r /var/www/html/* ./var/www/html/  
      - cp appspec.yml ./ 
      - mkdir -p ./scripts  
      - cp scripts/start_apache.sh ./scripts/  
      - cp scripts/install_dependencies.sh ./scripts/  
      - echo "Artifact prepared."

artifacts:
  files:
    - /**  
  discard-paths: no
