version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Starting the build process..."
      - yum update -y
      - yum install -y httpd php
      - systemctl start httpd
      - systemctl enable httpd

  build:
    commands:
      - echo "Building the application..."
      - echo "<?php echo 'Hello, this is a test'; ?>" > /var/www/html/index.php
      - echo "Build completed."

  post_build:
    commands:
      - echo "Preparing the artifact for deployment..."
      # Empaquetar los archivos en un ZIP sin crear nuevas carpetas
      - zip -r $CODEBUILD_ARTIFACTS_OUTPUT_PATH /var/www/html
      - zip -ur $CODEBUILD_ARTIFACTS_OUTPUT_PATH appspec.yml  # A침adir appspec.yml
      - zip -ur $CODEBUILD_ARTIFACTS_OUTPUT_PATH scripts/start_apache.sh  # A침adir script
      - zip -ur $CODEBUILD_ARTIFACTS_OUTPUT_PATH scripts/install_dependencies.sh  # A침adir otro script
      - echo "Artifact prepared."

artifacts:
  files:
    - $CODEBUILD_ARTIFACTS_OUTPUT_PATH  # Usa el archivo .zip autom치ticamente generado
  discard-paths: no
