version: 0.2
# Testing if I can create and index file and send it to the artifact
#The previous commit used the index.html which is in the GitHub repository
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Starting the build process..."
      - yum update -y
      - yum install -y httpd php
  build:
    commands:
      - echo "Building the application..."
      - echo "<?php echo 'Hello, this is a test'; ?>" > index.php
      - mkdir -p /var/www/html
      - cp index.php /var/www/html
  post_build:
    commands:
      - echo "Moving index.html"
artifacts:
  files:
    - appspec.yml
    - scripts/start_apache.sh
    - scripts/install_dependencies.sh
    - /var/www/html/index.php
  discard-paths: no
