version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Starting the build process..."
      - yum update -y
      - yum install -y httpd php
  build:
    commands:
      - echo "Building the application..."
      - echo "<?php echo 'Hello, this is a test'; ?>" > /var/www/html/index.php
      - echo "Build completed."
  post_build:
    commands:
      - echo "Artifact prepared."
      - mkdir -p /var/www/html
      - mv /var/www/html/index.php /var/www/html/index.php
artifacts:
  files:
    - appspec.yml
    - scripts/start_apache.sh
    - scripts/install_dependencies.sh
    - /var/www/html/index.php
  discard-paths: no
