version: 0.2
# Creates and index file insted of using the one in GitHub
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Starting the build process..."
      - yum update -y
      - yum install -y httpd php
  build:
    commands:
      - echo "Building the application..."
      - echo "<?php echo 'Hello, this is a test!'; ?>" > index.php
  post_build:
    commands:
      - echo "Running test object index..."
      - grep -Fq "Hello, this is test!" index.php     #the test wont passes
artifacts:
  files:
    - appspec.yml
    - scripts/start_apache.sh
    - scripts/install_dependencies.sh
    - index.php
  discard-paths: no
